
username: Vercel
icon_url: https://avatars.githubusercontent.com/u/14985020?s=48&v=4

#pretext: Triggered via {{eventName}} by {{actor}} {{or action "action"}} {{ref}} `{{diffRef}}`
#title: Vercel
#
#
#text: |
#  *<{{workflowRunUrl}}|Workflow _{{workflow}}_ job _{{jobName}}_ triggered by _{{eventName}}_ is _{{jobStatus}}_>* for <{{refUrl}}|`{{ref}}`>
#  {{#if description}}<{{diffUrl}}|`{{diffRef}}`> - {{description}}{{/if}}
#  {{#if payload.commits}}
#  *Commits*
#  {{#each payload.commits}}
#  <{{this.url}}|`{{truncate this.id 8}}`> - {{this.message}}
#  {{/each}}
#  {{/if}}
#
#fallback: |-
#  [GitHub] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}
#
#
#footer: >-
#  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}
#
#fields:
#  - title: Workflow
#    value: "<{{workflowUrl}}|{{workflow}}>"
#    short: true
#  - title: Git Ref
#    value: "{{ref}} ({{refType}})"
#  - title: Actor
#    value: "{{actor}}"
#    short: true
#  - title: Job Status
#    value: "{{jobStatus}}"
#    short: true
#  - title: Preview
#    value: "{{env.VERCEL_OUTPUT}}"
#    short: false
#
#colors:
#  success: '#5DADE2'
#  failure: '#884EA0'
#  cancelled: '#A569BD'
#  default: '#7D3C98'
#
#icons:
#  success: ':white_check_mark:'
#  failure: ':grimacing:'
#  cancelled: ':x:'
#  skipped: ':heavy_minus_sign:'
#  default: ':interrobang:'




pretext: Triggered via {{eventName}} by {{actor}} {{or action "action"}} {{ref}} `{{diffRef}}`
title: GitHub Actions
title_link: https://support.github.com

text: |
  *<{{workflowRunUrl}}|Workflow _{{workflow}}_ job _{{jobName}}_ triggered by _{{eventName}}_ is _{{jobStatus}}_>* for <{{refUrl}}|`{{ref}}`>
  {{#if description}}<{{diffUrl}}|`{{diffRef}}`> - {{description}}{{/if}}
  {{#if payload.commits}}
  *Commits*
  {{#each payload.commits}}
  <{{this.url}}|`{{truncate this.id 8}}`> - {{this.message}}
  {{/each}}
  {{/if}}

fallback: |-
  [GitHub] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}

fields:
  - title: Workflow
    value: "<{{workflowUrl}}|{{workflow}}>"
    short: true
  - title: Git Ref
    value: "{{ref}} ({{refType}})"
  - title: Actor
    value: "{{actor}}"
    short: true
  - title: Job Status
    value: "{{jobStatus}}"
    short: true
  - title: Preview
    value: "{{env.GITHUB_ACTOR}}"
    short: false

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}

colors:
  success: '#5DADE2'
  failure: '#884EA0'
  cancelled: '#A569BD'
  default: '#7D3C98'

icons:
  success: ':white_check_mark:'
  failure: ':grimacing:'
  cancelled: ':x:'
  skipped: ':heavy_minus_sign:'
  default: ':interrobang:'
