name: Check pull request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-bridger:
    name: Check bridger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Lint script
        run: yarn lint

      - name: Lint style
        run: yarn stylelint

      - name: Test build
        run: yarn build

