name: Deploy develop

on:
  pull_request:

env:
  OHO_VERSION: 1.3.5

jobs:
  deploy-develop:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Prepare
        run: |
          mkdir -p $HOME/.local/bin
          curl -LO https://github.com/masukomi/oho/releases/download/v${OHO_VERSION}/oho_v${OHO_VERSION}.tgz
          tar -zxvf oho_v${OHO_VERSION}.tgz -C ./
          mv oho_v${OHO_VERSION}/oho $HOME/.local/bin/
          rm -rf oho_v${OHO_VERSION}
          rm -rf oho_v${OHO_VERSION}.tgz

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:dev

      - name: Deploy
        id: deploy
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          mv build $REPO_NAME
          cd $REPO_NAME
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope itering link --confirm
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope itering deploy 2>&1 >/dev/null | tee deploy.log
          content=$(cat deploy.log)
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          content=$(echo $content | oho)
          echo ''
          echo "::set-output name=VERCEL_OUTPUT::$content"

      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: ${{ steps.deploy.outputs.VERCEL_OUTPUT }}
