name: Deploy develop

on:
  pull_request:

jobs:
  deploy-develop:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: fewensa/actions
          path: .github/actions

      - uses: ./.github/actions/smart-vercel
        name: Deploy to Vercel
        id: smart-vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          message: ${{ steps.smart-vercel.outputs.PREVIEW_OUTPUT }}

      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v1.5.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          VERCEL_OUTPUT: ${{ steps.smart-vercel.outputs.PREVIEW_LINK }}
        with:
          status: ${{ job.status }}
          channel: '#darwinia-apps'
          message: |
            Preview: ${{ steps.smart-vercel.outputs.PREVIEW_LINK }}
