name: Test CI

on:
  pull_request:
    branches: [master]

env:
  NODE_VERSION: 14.17.0

jobs:
  test-ci:
    name: Test CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: fewensa/actions
          path: .github/actions

      - uses: ./.github/actions/smart-vercel
        with:
          node_version: ${{ env.NODE_VERSION }}







